# Generated by Django 2.0.2 on 2018-04-08 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday formar: YYYY-mm-dd'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='Chen', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Whether the user can teach course in this website.', verbose_name='teacher status'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='Yao-Rong', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='mother_language',
            field=models.CharField(default='Chinese', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='time_zone',
            field=models.CharField(default='GMT+8 Taipei', max_length=20),
            preserve_default=False,
        ),
    ]
